package model;

import java.util.ArrayList;
import java.util.List;

/**
 * GP (General Practitioner) class representing a doctor in the healthcare system.
 *
 * @author Hrithik Chandra
 * @version 1.0
 */
public class GP extends User {

    // === GP-SPECIFIC ATTRIBUTES ===
    private String specialty;              // Medical specialty
    private String practiceName;           // Name of GP practice/surgery
    private List<String> prescriptions;    // List of prescriptions created
    private List<String> referrals;        // List of referrals created

    // === CONSTRUCTOR ===
    public GP(String userId, String name, String email, String phone, String specialty, String practiceName) {
        super(userId, name, email, phone);
        this.specialty = specialty;
        this.practiceName = practiceName;
        this.prescriptions = new ArrayList<>();
        this.referrals = new ArrayList<>();
    }

    // === OVERRIDE performRole() ===
    @Override
    public void performRole() {
        System.out.println("Dr. " + name + " is creating a prescription for a patient.");
    }

    // === GP-SPECIFIC METHODS ===

    public void createPrescription(String patientId, String medication, String dosage) {
        String prescription = "Prescription for " + patientId + ": " + medication + " (" + dosage + ")";
        prescriptions.add(prescription);
        System.out.println("Prescription created by Dr. " + name);
    }

    public void updatePatientRecord(String patientId) {
        System.out.println("Dr. " + name + " has updated record for patient " + patientId);
    }

    public void generateReferral(String patientId, String specialistType) {
        String referral = "Referral from " + name + " to " + specialistType + " for patient " + patientId;
        referrals.add(referral);
        System.out.println("Referral generated by Dr. " + name);
    }

    public void manageAppointments() {
        System.out.println("Dr. " + name + " is managing appointments.");
    }

    public void orderLabTest(String patientId, String testType) {
        System.out.println("Dr. " + name + " has ordered " + testType + " test for patient " + patientId);
    }

    // === GETTERS & SETTERS ===

    public String getSpecialty() {
        return specialty;
    }

    public String getPracticeName() {
        return practiceName;
    }

    public List<String> getPrescriptions() {
        return new ArrayList<>(prescriptions);
    }

    public List<String> getReferrals() {
        return new ArrayList<>(referrals);
    }
}
